### PR TITLE
Win Probability Updates

### PR DESCRIPTION
**Pull request by mattchorlian**
Win probability updates:

- [x] Add category win probabilities (historic data) to Compare page
- [ ] Add category win probabilities (Last 15 data) to Compare page
- [ ] Add average of both to Scoreboard

### CODE REVIEW

**Comment by E-Feng** [comment]
There should be a way to combine these 2 tables since they have the same axes. But the aggregated win% might not be as useful as having the separate win% for each individual cat. It that were another column on the right table, it gives users a way to gauge whether a cat is worth streaming for.

**Comment by E-Feng** [comment]
Looks good so far. Win % that are 50/50 are not colored at all, should one be red? I'd change "Cat Win %" to just Win%, then decide later if roster was used as another metric for calculation.

**Comment by mattchorlian** [comment]
I'll need to think about how to best get an aggregate, whole-team 'Last 15' w/ standard deviations.  Another option could have a toggle for 'Last X Weeks' and only calculate winPer with those weeks.

**Comment by E-Feng** [comment]
> I'll need to think about how to best get an aggregate, whole-team 'Last 15' w/ standard deviations. Another option could have a toggle for 'Last X Weeks' and only calculate winPer with those weeks.

Last15 seems standard for current rankings/ratings. For these rough percentages it should be best to use a singular value to avoid confusion and complexity.

**Comment by mattchorlian** [comment]
I *think* properly using Last15 to calculate win percentages would require:

For each player on team:
- Calculate mean for each category (sum and divide by games played)
- Calculate standard deviation for each category (using mean and # of games played in last 15 days)

For each team:
- Sum the means of each player in each category to get projected 15-day scores for each team
- Aggregate the standard deviations: each players' cat's stddev -> aggregate 'Last15' stddev for each category.  This would be the most complex part

Now we have a 'Last 15' mean and standard deviation for each category.

Then we could calculate category win % with that data, but that would mean it's not entirely accurate since we're really calculating category win % over a 15 day matchup.   I'm sure there's a way to scale each mean/stdev back to 7 days but I'd need to look into it a bit more.  I guess that's a long winded way of saying it looks pretty complicated unless I'm missing something obvious.  

I'll mark this as ready if you want to merge it in as is.  I can start laying the foundation for the last 15 implementation in a separate MR

**Comment by E-Feng** [comment]
> I _think_ properly using Last15 to calculate win percentages would require:
> 
> For each player on team:
> 
> * Calculate mean for each category (sum and divide by games played)
> * Calculate standard deviation for each category (using mean and # of games played in last 15 days)
> 
> For each team:
> 
> * Sum the means of each player in each category to get projected 15-day scores for each team
> * Aggregate the standard deviations: each players' cat's stddev -> aggregate 'Last15' stddev for each category.  This would be the most complex part
> 
> Now we have a 'Last 15' mean and standard deviation for each category.
> 
> Then we could calculate category win % with that data, but that would mean it's not entirely accurate since we're really calculating category win % over a 15 day matchup. I'm sure there's a way to scale each mean/stdev back to 7 days but I'd need to look into it a bit more. I guess that's a long winded way of saying it looks pretty complicated unless I'm missing something obvious.
> 
> I'll mark this as ready if you want to merge it in as is. I can start laying the foundation for the last 15 implementation in a separate MR

No, you're right. I forgot what was available in the player data and only a singular stats for Last15 is available. Obtaining several gamescores is a bit of work from the backend side.

I'll take a look at the current PR.

**Comment by E-Feng** [comment]
Also as a note, I have ported in a quick schedule in the common data which you can pull from the query (see messageboard for common data). These provide number of games for the teams in the current week which will be useful when looking at individual contributions for probabilities.

**Review by E-Feng — APPROVED** [review]

**Pull request merged**
