### PR TITLE
categoryUtils update: fix getCatInverse function

### PR DESCRIPTION
**Pull request by mattchorlian**
Looks like filter() returns an array, so the code should index into that array then access the inverse field

### CODE REVIEW

**Comment by mattchorlian** [comment]
Or maybe something like this is slightly more robust 
`  cat_obj = categoryDetails.filter((o) => o.name === cat)[0]
  if (cat_obj) return cat_obj.inverse;
  // Default to false if there is an issue getting category object?
  return false`

**Comment by E-Feng** [comment]
Was this issue affecting a display, it seems its only used for Compare which seems to be alright on quick glance.

**Comment by mattchorlian** [comment]
I saw it specifically for the TO category where higher turnover numbers were greener than lower turnover numbers when it should be the other way around.

**Comment by E-Feng** [comment]
Got it, I see it now. Only looked at the summary side and it looks like I did a more hardcoded version for the inverse there. If you don't mind, you can change CompareSummaryTable.js Line 132 to use the function too so it'll be more robust.

**Pull request merged**
